Make libwrap support optional
Make using libwrap an option when running configure. Not everyone needs
this so making it an option is best. Disabling libwrap can cut down on
complexity, processing necessary per connection and potential bugs in
the libwrap code. It is still enabled by default so this should not
break any existing configure strings.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -846,6 +846,11 @@ if test -n "$ac_init_help"; then
    esac
   cat <<\_ACEOF
 
+Optional Features:
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+  --disable-libwrap       disable libwrap support
+
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
@@ -5597,76 +5602,6 @@ if test $ac_cv_lib_socket_socket = yes; then
 fi
 
 
-echo "$as_me:$LINENO: checking for main in -lwrap" >&5
-echo $ECHO_N "checking for main in -lwrap... $ECHO_C" >&6
-if test "${ac_cv_lib_wrap_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lwrap  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_wrap_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_wrap_main=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_wrap_main" >&5
-echo "${ECHO_T}$ac_cv_lib_wrap_main" >&6
-if test $ac_cv_lib_wrap_main = yes; then
-
-	LIBWRAPLIBS="$LIBWRAPLIBS -lwrap"
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_LIBWRAP 1
-_ACEOF
-
-
-fi
-
-
 
 
 
@@ -6060,6 +5995,96 @@ echo "${ECHO_T}int" >&6
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 
+echo "$as_me:$LINENO: checking whether to include libwrap support" >&5
+echo $ECHO_N "checking whether to include libwrap support... $ECHO_C" >&6
+# Check whether --enable-libwrap or --disable-libwrap was given.
+if test "${enable_libwrap+set}" = set; then
+  enableval="$enable_libwrap"
+   case "$enableval" in
+    no) echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; WITH_LIBWRAP= ;;
+    *) echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; WITH_LIBWRAP=1 ;;
+   esac
+else
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6;   WITH_LIBWRAP=1
+fi;
+
+# Decide whether to look for libwrap libraries
+if test -n "$WITH_LIBWRAP"; then
+	echo "$as_me:$LINENO: checking for main in -lwrap" >&5
+echo $ECHO_N "checking for main in -lwrap... $ECHO_C" >&6
+if test "${ac_cv_lib_wrap_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lwrap  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_wrap_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_wrap_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_wrap_main" >&5
+echo "${ECHO_T}$ac_cv_lib_wrap_main" >&6
+if test $ac_cv_lib_wrap_main = yes; then
+
+		LIBWRAPLIBS="$LIBWRAPLIBS -lwrap"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBWRAP 1
+_ACEOF
+
+
+fi
+
+
+fi
+
 
 # Check whether --with-mcrypt-lib or --without-mcrypt-lib was given.
 if test "${with_mcrypt_lib+set}" = set; then
@@ -6077,7 +6102,6 @@ if test "${with_mcrypt_inc+set}" = set; then
 	CFLAGS="${CFLAGS} -I${withval}"
 
 fi;
-
 
 MCRYPTLIBFOUND=yep
 
